# shellcheck shell=bash
# Paths / EREs / globs treated as regeneratable (strip from du + rsync).
#
# Doctrine: back up source of truth + lockfiles/config; skip install trees,
# caches, build outputs, and temp dirs. Restore reinstalls from manifests
# (see maintainer/phases/10-pm-tools-research.md — standing research).
#
# Per-directory .gitignore is also honored at rsync (unless --no-gitignore).

# Concrete path templates (expanded under home / absolute)
# Prefer *install/cache* leaves over whole tool homes when config/state must stay.
CONSTRAINTS_REGENERABLE_TARGETS=(
  .cache
  .npm
  .cargo/registry
  .cargo/git
  .rustup
  .local/share/pipx
  .local/share/pnpm
  .local/share/Trash
  .local/share/uv
  .local/share/mise/installs
  .local/share/mise/downloads
  .local/share/flatpak
  .local/share/containers
  .local/share/NuGet
  .local/share/JetBrains
  .local/lib
  .asdf/installs
  .asdf/downloads
  .nvm/versions
  .bun/install/cache
  .nuget/packages
  .composer/cache
  .cache/pip
  .cache/pypoetry
  .cache/pre-commit
  .cache/typescript
  .cache/yarn
  .cache/HuggingFace
  .cache/whisper
  .cache/torch
  .cache/mesa_shader_cache
  .cursor-server
  .vscode-server
  .vscode-remote
  go
  go/pkg
  go/bin
  go/pkg/mod
  /var/cache/apt
  /var/cache/dnf
  /var/cache/yum
  /var/cache/pacman
)

# Regex patterns (ERE) for matching discovered paths
CONSTRAINTS_REGENERABLE_REGEXES=(
  '/node_modules(/|$)'
  '/\.next(/|$)'
  '/\.nuxt(/|$)'
  '/\.output(/|$)'
  '/\.turbo(/|$)'
  '/\.vercel(/|$)'
  '/\.svelte-kit(/|$)'
  '/\.angular(/|$)'
  '/\.vite(/|$)'
  '/\.parcel-cache(/|$)'
  '/\.sass-cache(/|$)'
  '/\.eslintcache(/|$)'
  '/\.stylelintcache(/|$)'
  '/\.wrangler(/|$)'
  '/\.mf(/|$)'
  '/\.miniflare(/|$)'
  '/\.serverless(/|$)'
  '/\.aws-sam(/|$)'
  '/cdk\.out(/|$)'
  '/\.pulumi(/|$)'
  '/\.docusaurus(/|$)'
  '/storybook-static(/|$)'
  '/\.nox(/|$)'
  '/\.venv(/|$)'
  '/venv(/|$)'
  '/__pycache__(/|$)'
  '/__pypackages__(/|$)'
  '/site-packages(/|$)'
  '/\.eggs(/|$)'
  '/\.tox(/|$)'
  '/\.mypy_cache(/|$)'
  '/\.pytest_cache(/|$)'
  '/\.ruff_cache(/|$)'
  '/\.hypothesis(/|$)'
  '/\.pytype(/|$)'
  '/\.pyre(/|$)'
  '/\.ipynb_checkpoints(/|$)'
  '/\.pdm-build(/|$)'
  '/htmlcov(/|$)'
  '/\.nyc_output(/|$)'
  '/\.coverage(/|$)'
  '/target(/|$)'
  '/dist(/|$)'
  '/build(/|$)'
  '/out(/|$)'
  '/coverage(/|$)'
  '/bower_components(/|$)'
  '/\.cache(/|$)'
  '/\.tmp(/|$)'
  '/\.temp(/|$)'
  '/\.npm(/|$)'
  '/\.pnpm-store(/|$)'
  '/\.local/share/pnpm(/|$)'
  '/\.local/lib(/|$)'
  '/\.local/share/mise/installs(/|$)'
  '/\.local/share/mise/downloads(/|$)'
  '/\.asdf/installs(/|$)'
  '/\.asdf/downloads(/|$)'
  '/\.nvm/versions(/|$)'
  '/\.yarn/cache(/|$)'
  '/\.yarn/unplugged(/|$)'
  '/\.bun/install/cache(/|$)'
  '/\.cargo/registry(/|$)'
  '/\.cargo/git(/|$)'
  '/\.rustup(/|$)'
  '/go/pkg(/|$)'
  '/go/bin(/|$)'
  '/go/pkg/mod(/|$)'
  '/\.local/share/pipx(/|$)'
  '/\.local/share/Trash(/|$)'
  '/\.local/share/uv(/|$)'
  '/\.local/share/NuGet(/|$)'
  '/\.nuget/packages(/|$)'
  '/\.composer/cache(/|$)'
  '/var/cache/apt(/|$)'
  '/var/cache/dnf(/|$)'
  '/var/cache/yum(/|$)'
  '/var/cache/pacman(/|$)'
  '/\.gradle(/|$)'
  '/\.m2/repository(/|$)'
  '/vendor/bundle(/|$)'
  '/\.bundle(/|$)'
  '/\.dart_tool(/|$)'
  '/\.pub-cache(/|$)'
  '/\.terraform(/|$)'
  '/\.terragrunt-cache(/|$)'
  '/\.stack-work(/|$)'
  '/_build(/|$)'
  '/\.elixir_ls(/|$)'
  '/Pods(/|$)'
  '/DerivedData(/|$)'
  '/\.cxx(/|$)'
  '/cmake-build-(debug|release)(/|$)'
  '/\.idea(/|$)'
  '/\.vs(/|$)'
  '/\.jekyll-cache(/|$)'
  '/_site(/|$)'
  '/\.cursor-server(/|$)'
  '/\.vscode-server(/|$)'
  '/\.vscode-remote(/|$)'
  '/\.net(/|$)'
  '\.egg-info(/|$)'
)

# Basename / path-component globs for GNU du --exclude= and rsync --exclude
CONSTRAINTS_DU_EXCLUDE_GLOBS=(
  node_modules
  .next
  .nuxt
  .output
  .turbo
  .vercel
  .svelte-kit
  .angular
  .vite
  .parcel-cache
  .sass-cache
  .eslintcache
  .stylelintcache
  .wrangler
  .mf
  .miniflare
  .serverless
  .aws-sam
  cdk.out
  .pulumi
  .docusaurus
  storybook-static
  .nox
  .venv
  venv
  __pycache__
  __pypackages__
  site-packages
  .eggs
  .tox
  .mypy_cache
  .pytest_cache
  .ruff_cache
  .hypothesis
  .pytype
  .pyre
  .ipynb_checkpoints
  .pdm-build
  htmlcov
  .nyc_output
  target
  dist
  build
  out
  coverage
  bower_components
  .cache
  .tmp
  .temp
  .npm
  .pnpm-store
  .dart_tool
  .pub-cache
  .terraform
  .terragrunt-cache
  .stack-work
  _build
  .elixir_ls
  Pods
  DerivedData
  .cxx
  .gradle
  .m2
  vendor
  Trash
  .jekyll-cache
  _site
  pnpm
  .rustup
  .nuget
  .cursor-server
  .vscode-server
  .vscode-remote
  .net
  # Version-manager install trees (mise/asdf use these basenames under share/)
  installs
  downloads
)

# File / glob patterns for rsync + GNU du (not bare basenames)
CONSTRAINTS_FILE_EXCLUDE_GLOBS=(
  '*.pyc'
  '*.pyo'
  '*.tmp'
  '*.temp'
  '*.swp'
  '*.swo'
  '*~'
  '*.tsbuildinfo'
  '*.egg-info'
  '.DS_Store'
  'Thumbs.db'
  '*.class'
  '*.o'
  '*.a'
  'core'
  'core.[0-9]*'
)
